name: Playwright WebKit Iframe Cookie Issue

on:
  push:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Allow Node.js to use port 80
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo setcap 'cap_net_bind_service=+ep' $(which node)

      - name: Install system dependencies
        run: npx playwright install-deps

      - name: Install dependencies
        run: npm ci

      - name: Configure hosts file
        run: |
          echo "127.0.0.1 example.test" | sudo tee -a /etc/hosts
          echo "127.0.0.1 sub.example.test" | sudo tee -a /etc/hosts

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Get environment info
        run: npx envinfo --preset playwright

      - name: Start test server
        run: npm run server &

      - name: Run tests
        run: npm test

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.os }}
          path: playwright-report/
          retention-days: 30
